### ISSUE TITLE
OSError: (External)  Cublas error, `CUBLAS_STATUS_INVALID_VALUE`

### ISSUE THREAD

**Issue by jeffzhengye** [PaddlePaddle/PaddleFormers#1337]
Since tensorflow is running very well on my machine, I assume the env is configured correctly.
What could be the problems and how I may fix it?
`
    results = self.detector.object_detection(images = [ori_img], use_gpu = self.use_gpu, score_thresh = self.threshold, visualization=False)
  File "/home/user/anaconda3/lib/python3.7/site-packages/paddlehub/compat/paddle_utils.py", line 220, in runner
    return func(*args, **kwargs)
  File "/home/user/.paddlehub/modules/yolov3_resnet50_vd_coco2017/module.py", line 211, in object_detection
    [image_tensor, im_size_tensor])
OSError: (External)  Cublas error, `CUBLAS_STATUS_INVALID_VALUE`. An unsupported value or parameter was passed to the function (a negative vector size, for example).  (at /paddle/paddle/fluid/platform/cuda_helper.h:93)
`

**Comment by Bob-AFei** [comment]
Hi all,

just for a memo, PyTorch is running well on my machine too.

By the way, I found Pr. Ye and I both used python3.7 or the conda environment. May it lead to this issue?
Professor Ye, did you try docker to run this code before?

At last, many thanks. : )



At 2021-03-23 19:39:14, "Jeffery Ye" ***@***.***> wrote:

Since tensorflow is running very well on my machine, I assume the env is configured correctly.
What could be the problems and how I may fix it?
results = self.detector.object_detection(images = [ori_img], use_gpu = self.use_gpu, score_thresh = self.threshold, visualization=False) File "/home/user/anaconda3/lib/python3.7/site-packages/paddlehub/compat/paddle_utils.py", line 220, in runner return func(*args, **kwargs) File "/home/user/.paddlehub/modules/yolov3_resnet50_vd_coco2017/module.py", line 211, in object_detection [image_tensor, im_size_tensor]) OSError: (External) Cublas error,CUBLAS_STATUS_INVALID_VALUE. An unsupported value or parameter was passed to the function (a negative vector size, for example). (at /paddle/paddle/fluid/platform/cuda_helper.h:93)

**Comment by haoyuying** [comment]
请问您用的paddle，paddlehub及python，cudnn和cuda 的版本是什么呢？
我验证时候使用的是paddlepaddle-gpu=2.0.1， paddlehub=2.0.0， cuda=10.2， cudnn=7.6.5， python=3.8.5，没有出现您说的问题。验证脚本及验证方法：
```
import paddlehub as hub
import cv2

object_detector = hub.Module(name="yolov3_resnet50_vd_coco2017")
result = object_detector.object_detection(images=[cv2.imread('2007_000175.jpg')],use_gpu=True)
print(result)
```
在命令行输入`CUDA_VISIBLE_DEVICES=0 python test.py`

目前您存在的问题初步判定有两个方面，环境配置有问题，paddle和cuda的版本及cudnn版本不匹配，第二种是在执行时候没有设定好CUDA_VISIBLE_DEVICES

**Comment by jeffzhengye** [comment]
This problem is really due to the version mismatching.  The version number cannot be higher or lower with even a minor version number. 
Read its doc very carefully and do as it says exactly since the doc is not very well written. 

Overall, it's much harder than that of tensorflow for the configuration. I believe its the platform's responsibility to output more useful information for debug (I guess it's easy to check the mismatching).

**Comment by jeffzhengye** [comment]
> This problem is really due to the version mismatching. The version number cannot be higher or lower with even a minor version number.
> Read its doc very carefully and do as it says exactly since the doc is not very well written.
> 
> Overall, it's much harder than that of tensorflow for the configuration. I believe its the platform's responsibility to output more useful information for debug (I guess it's easy to check the mismatching).

Although this problem has been fixed, this thread cannot provide any useful information for other users. It makes paddle hard to use when you get a problem.

**Comment by Maojianzeng** [comment]
I meet a same problem:

2022-04-29 18:05:40 [INFO]      Starting to read file list from dataset...
2022-04-29 18:05:40 [INFO]      1981 samples in file MyDataset/train.json, including 1981 positive samples and 0 negative samples.
loading annotations into memory...
Done (t=0.07s)
creating index...
index created!
2022-04-29 18:05:40 [INFO]      Starting to read file list from dataset...
2022-04-29 18:05:40 [INFO]      495 samples in file MyDataset/val.json, including 495 positive samples and 0 negative samples.
W0429 18:05:40.970075 12979 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.0, Runtime API Version: 11.0
W0429 18:05:40.975056 12979 device_context.cc:422] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "train.py", line 38, in <module>
    model = pdx.det.FasterRCNN(num_classes=num_classes, backbone='ResNet101')
  File "/root/.local/lib/python3.7/site-packages/paddlex/cv/models/detector.py", line 854, in __init__
    dcn_v2_stages=dcn_v2_stages)
  File "/root/.local/lib/python3.7/site-packages/paddlex/cv/models/detector.py", line 100, in _get_backbone
    backbone = getattr(ppdet.modeling, backbone_name)(**params)
  File "/root/.local/lib/python3.7/site-packages/paddlex/ppdet/modeling/backbones/resnet.py", line 528, in __init__
    lr=1.0))
  File "/root/.local/lib/python3.7/site-packages/paddlex/ppdet/modeling/backbones/resnet.py", line 69, in __init__
    bias_attr=False)
  File "/root/.local/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 646, in __init__
    data_format=data_format)
  File "/root/.local/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 135, in __init__
    default_initializer=_get_default_param_initializer())
  File "/root/.local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 412, in create_parameter
    default_initializer)
  File "/root/.local/lib/python3.7/site-packages/paddle/fluid/layer_helper_base.py", line 374, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/root/.local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2895, in create_parameter
    initializer(param, self)
  File "/root/.local/lib/python3.7/site-packages/paddle/fluid/initializer.py", line 366, in __call__
    stop_gradient=True)
  File "/root/.local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2925, in append_op
    kwargs.get("stop_gradient", False))
  File "/root/.local/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
OSError: (External)  Cublas error, `CUBLAS_STATUS_INVALID_VALUE`. An unsupported value or parameter was passed to the function (a negative vector size, for example).  (at /paddle/paddle/fluid/platform/cuda_helper.h:107)

**Comment by Maojianzeng** [comment]
>

> I meet a same problem:
> 
> 2022-04-29 18:05:40 [INFO] Starting to read file list from dataset... 2022-04-29 18:05:40 [INFO] 1981 samples in file MyDataset/train.json, including 1981 positive samples and 0 negative samples. loading annotations into memory... Done (t=0.07s) creating index... index created! 2022-04-29 18:05:40 [INFO] Starting to read file list from dataset... 2022-04-29 18:05:40 [INFO] 495 samples in file MyDataset/val.json, including 495 positive samples and 0 negative samples. W0429 18:05:40.970075 12979 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.0, Runtime API Version: 11.0 W0429 18:05:40.975056 12979 device_context.cc:422] device: 0, cuDNN Version: 7.6. Traceback (most recent call last): File "train.py", line 38, in model = pdx.det.FasterRCNN(num_classes=num_classes, backbone='ResNet101') File "/root/.local/lib/python3.7/site-packages/paddlex/cv/models/detector.py", line 854, in **init** dcn_v2_stages=dcn_v2_stages) File "/root/.local/lib/python3.7/site-packages/paddlex/cv/models/detector.py", line 100, in _get_backbone backbone = getattr(ppdet.modeling, backbone_name)(**params) File "/root/.local/lib/python3.7/site-packages/paddlex/ppdet/modeling/backbones/resnet.py", line 528, in **init** lr=1.0)) File "/root/.local/lib/python3.7/site-packages/paddlex/ppdet/modeling/backbones/resnet.py", line 69, in **init** bias_attr=False) File "/root/.local/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 646, in **init** data_format=data_format) File "/root/.local/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 135, in **init** default_initializer=_get_default_param_initializer()) File "/root/.local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 412, in create_parameter default_initializer) File "/root/.local/lib/python3.7/site-packages/paddle/fluid/layer_helper_base.py", line 374, in create_parameter **attr._to_kwargs(with_initializer=True)) File "/root/.local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2895, in create_parameter initializer(param, self) File "/root/.local/lib/python3.7/site-packages/paddle/fluid/initializer.py", line 366, in **call** stop_gradient=True) File "/root/.local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2925, in append_op kwargs.get("stop_gradient", False)) File "/root/.local/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op not stop_gradient) OSError: (External) Cublas error, `CUBLAS_STATUS_INVALID_VALUE`. An unsupported value or parameter was passed to the function (a negative vector size, for example). (at /paddle/paddle/fluid/platform/cuda_helper.h:107)

I solve the problem by:
Successfully uninstalled paddlepaddle-gpu-2.1.2.post110
Successfully installed paddlepaddle-gpu-2.1.2.post101
Maybe the project is suit for cuda10.1, not 11.0.
